--------------------------------
-- Schema Creation and Table Setup
-- Order matters: users first, then tables that depend on it
---------------------------------

--------------------------------
-- Create public.users table
---------------------------------

-- Drop if exists (no OBJECT_ID in Postgres)
DROP TABLE IF EXISTS public.users CASCADE;

CREATE TABLE public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    firstname  VARCHAR(50),
    lastname  VARCHAR(50) NOT NULL,
    company  VARCHAR(100),
    userpassword VARCHAR(255) NOT NULL,
    userrole VARCHAR(20) NOT NULL DEFAULT 'USER',
    enabled BOOLEAN NOT NULL DEFAULT true,
    forcepasswordupdate BOOLEAN NOT NULL DEFAULT true,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_login TIMESTAMP NULL
);

-- Create unique index on username to prevent duplicate usernames
-- This ensures data integrity and provides optimal query performance
-- Note: CONCURRENTLY cannot be used in schema.sql as it runs in a transaction
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_username_unique 
ON public.users (username);

-----------------------------------
-- Create public.dropdownvalues table
-----------------------------------

-- Drop if exists (no OBJECT_ID in Postgres)
DROP TABLE IF EXISTS public.dropdownvalues CASCADE;

-- Recreate with lowercase column names
CREATE TABLE public.dropdownvalues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR(50) NOT NULL,
    itemvalue VARCHAR(255) NOT NULL,
    displayorder INTEGER NOT NULL DEFAULT 0,
    isactive BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_dropdownvalues_category_value UNIQUE (category, itemvalue)
);

--------------------------------
-- Create public.taskactivity table
---------------------------------

-- Drop if exists (no OBJECT_ID in Postgres)
DROP TABLE IF EXISTS public.taskactivity CASCADE;

-- Recreate with lowercase column names
CREATE TABLE public.taskactivity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    taskdate DATE NOT NULL,
    client VARCHAR(255) NOT NULL,
    project VARCHAR(255) NOT NULL,
    phase VARCHAR(255) NOT NULL,
    taskhours NUMERIC(4, 2) NOT NULL,
    details VARCHAR(255),
    username VARCHAR(50) NOT NULL,
    CONSTRAINT pk_taskactivity PRIMARY KEY (id),
    CONSTRAINT uq_taskactivity UNIQUE (taskdate, client, project, phase, details, username)
);

-- Add foreign key constraint from taskactivity to users
-- This prevents deletion of users who have task activities
ALTER TABLE public.taskactivity
ADD CONSTRAINT fk_taskactivity_username
FOREIGN KEY (username) REFERENCES public.users(username)
ON DELETE RESTRICT
ON UPDATE CASCADE;