--------------------------------
-- Schema Creation and Table Setup
--
-- This script is ONLY for initial database setup or complete rebuild.
-- DO NOT run this on a database with existing data!
--
-- Spring Boot Configuration:
-- - application.properties: spring.sql.init.mode=never (SAFE - won't run)
-- - application-local.properties: inherits never (SAFE - won't run)
-- - application-aws.properties: spring.sql.init.mode=never (SAFE - won't run)
-- - application-docker.properties: spring.sql.init.mode=always (RUNS THIS FILE - fresh container only)
--
-- Order matters: users first, then tables that depend on it
---------------------------------

--------------------------------
-- Create public.users table
---------------------------------

-- DROP statements removed for safety - only use this for initial setup
-- If you need to recreate tables, drop them manually via psql or pgAdmin
-- DROP TABLE IF EXISTS public.users CASCADE;

CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    firstname  VARCHAR(50),
    lastname  VARCHAR(50) NOT NULL,
    company  VARCHAR(100),
    userpassword VARCHAR(255) NOT NULL,
    userrole VARCHAR(20) NOT NULL DEFAULT 'USER',
    enabled BOOLEAN NOT NULL DEFAULT true,
    forcepasswordupdate BOOLEAN NOT NULL DEFAULT true,
    expiration_date DATE NULL,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_login TIMESTAMP NULL
);

-- Create unique index on username to prevent duplicate usernames
-- This ensures data integrity and provides optimal query performance
-- Note: CONCURRENTLY cannot be used in schema.sql as it runs in a transaction
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_username_unique 
ON public.users (username);

-----------------------------------
-- Create public.dropdownvalues table
-----------------------------------

-- DROP statements removed for safety - only use this for initial setup
-- If you need to recreate tables, drop them manually via psql or pgAdmin
-- DROP TABLE IF EXISTS public.dropdownvalues CASCADE;

-- Create with lowercase column names
CREATE TABLE IF NOT EXISTS public.dropdownvalues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR(50) NOT NULL,
    itemvalue VARCHAR(255) NOT NULL,
    displayorder INTEGER NOT NULL DEFAULT 0,
    isactive BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_dropdownvalues_category_value UNIQUE (category, itemvalue)
);

--------------------------------
-- Create public.taskactivity table
---------------------------------

-- DROP statements removed for safety - only use this for initial setup
-- If you need to recreate tables, drop them manually via psql or pgAdmin
-- DROP TABLE IF EXISTS public.taskactivity CASCADE;

-- Create with lowercase column names
CREATE TABLE IF NOT EXISTS public.taskactivity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    taskdate DATE NOT NULL,
    client VARCHAR(255) NOT NULL,
    project VARCHAR(255) NOT NULL,
    phase VARCHAR(255) NOT NULL,
    taskhours NUMERIC(4, 2) NOT NULL,
    details VARCHAR(255),
    username VARCHAR(50) NOT NULL,
    CONSTRAINT pk_taskactivity PRIMARY KEY (id),
    CONSTRAINT uq_taskactivity UNIQUE (taskdate, client, project, phase, details, username)
);

-- Add foreign key constraint from taskactivity to users (if not already exists)
-- This prevents deletion of users who have task activities
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_taskactivity_username'
    ) THEN
        ALTER TABLE public.taskactivity
        ADD CONSTRAINT fk_taskactivity_username
        FOREIGN KEY (username) REFERENCES public.users(username)
        ON DELETE RESTRICT
        ON UPDATE CASCADE;
    END IF;
END $$;

--------------------------------
-- Create indexes on task_activity table for improved query performance
-- These indexes benefit current filtering/sorting and future reporting features
--------------------------------

-- Index on task_date (most frequently filtered/sorted column - Dashboard, Reports)
CREATE INDEX IF NOT EXISTS idx_taskactivity_task_date ON public.taskactivity(taskdate);

-- Index on username (for user-specific queries - GUEST users, user reports)
CREATE INDEX IF NOT EXISTS idx_taskactivity_username ON public.taskactivity(username);

-- Index on client (for client filtering in dropdowns and reports)
CREATE INDEX IF NOT EXISTS idx_taskactivity_client ON public.taskactivity(client);

-- Index on project (for project filtering in dropdowns and reports)
CREATE INDEX IF NOT EXISTS idx_taskactivity_project ON public.taskactivity(project);

-- Index on phase (for phase filtering in dropdowns and reports)
CREATE INDEX IF NOT EXISTS idx_taskactivity_phase ON public.taskactivity(phase);

-- Composite index for common filter combination (date + user)
-- Optimizes queries like "show me my tasks this week"
CREATE INDEX IF NOT EXISTS idx_taskactivity_date_user ON public.taskactivity(taskdate, username);

-- Composite index for common grouping (client + project)
-- Optimizes queries that group by client and project
CREATE INDEX IF NOT EXISTS idx_taskactivity_client_project ON public.taskactivity(client, project);

