-----------------------------------
-- Create dbo.DropdownValues table
-----------------------------------

-- Ensure the dbo schema exists
CREATE SCHEMA IF NOT EXISTS dbo;

-- Drop if exists (no OBJECT_ID in Postgres)
DROP TABLE IF EXISTS dbo."DropdownValues";

-- Recreate with CamelCase column names preserved
CREATE TABLE dbo."DropdownValues" (
    "RECID"        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "category"     VARCHAR(50)  NOT NULL,
    "value"        VARCHAR(255) NOT NULL,
    "displayOrder" INTEGER      NOT NULL DEFAULT 0,
    "isActive"     BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT "UK_DropdownValues_Category_Value" UNIQUE ("category", "value")
);
