--------------------------------
-- Create dbo.TaskActivity table
---------------------------------

-- Ensure the dbo schema exists
CREATE SCHEMA IF NOT EXISTS dbo;

-- Drop if exists (no OBJECT_ID in Postgres)
DROP TABLE IF EXISTS dbo."TaskActivity";

-- Recreate with CamelCase column names preserved
CREATE TABLE dbo."TaskActivity" (
    "RECID"     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "taskDate"  DATE NOT NULL,
    "client"    VARCHAR(255) NOT NULL,
    "project"   VARCHAR(255) NOT NULL,
    "phase"     VARCHAR(255) NOT NULL,
    "hours"     NUMERIC(4, 2) NOT NULL,
    "details"   VARCHAR(255) NOT NULL,
    "username"  VARCHAR(50) NOT NULL,
    CONSTRAINT "PK_TaskActivity" PRIMARY KEY ("RECID"),
    CONSTRAINT "UQ_TaskActivity" UNIQUE ("taskDate", "client", "project", "phase", "details")
);